version: '3'
volumes:
  pgdata:
  static_volume:

services:
  python:
    build:
      context: .
      dockerfile: docker/python/Dockerfile
    image: xnandersson/django-greenfield
    volumes:
     - ./src:/src
     - static_volume:/src/staticfiles
    ports:
     - 8000:8000
    links:
     - postgres
     - dc
    command: ["gunicorn", "--bind=0.0.0.0", "greenfield.wsgi:application"]
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: greenfield
      POSTGRES_DB: greenfield
      POSTGRES_PASSWORD: greenfield
    volumes:
     - pgdata:/var/lib/postgresql/data
    ports:
     - 5432:5432
  dc:
    build:
      context: https://github.com/xnandersson/docker-dc.git
    image: xnandersson/dc:latest
    privileged: true
    environment:
      SAMBA_DOMAIN: openforce
      SAMBA_HOST_NAME: dc
      SAMBA_ADMINPASS: Abc123!
      SAMBA_REALM: OPENFORCE.ORG
  nginx:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    image: xnandersson/django-greenfield-nginx
    ports:
     - 80:80
    links:
     - python
    volumes:
     - static_volume:/src/staticfiles
